server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: authorization
          uri: lb://authorization
          predicates:
            - Path=/songsWS/rest/auth/**
        - id: song-service
          uri: lb://song-service
          predicates:
            - Path=/songsWS/rest/songs/**
        - id: song-service
          uri: lb://song-service
          predicates:
            - Path=/songsWS/rest/songLists/**
        - id: concert-service
          uri: lb://concert-service
          predicates:
            - Path=/songsWS/rest/tickets/**
        - id: concert-service
          uri: lb://concert-service
          predicates:
            - Path=/songsWS/rest/concerts/**